config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
   
  scope '/', controller: :welcome do
    get 'index'
    get 'about'
    get 'calculate'
    get 'promotion'
    post 'confirmation'
  end

  scope '/', controller: :calculators do
    get 'index'
  end
  

  namespace :admin do
    resources :products
  end
  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @page_title = 'Bjic: быстрая, качественная и недорогая уборка Вашего дома'
  end

  def calculate
    @page_title = 'Заказать уборку'

    #binding pry
    @general_products = Product.where(additional: false).order(:visible_order)
    @additional_products = Product.where(additional: true).order(:visible_order)

  end  

  def confirmation

    @order = Order.new(request_params)

    # binding.pry
    # @order_item = @order.order_items.build(params[:order][:order_item])
    # binding.pry
    respond_to do |format|
      if @order.save
        general_product_id = params[:order][:product_id]
        OrderItem.create!(product_id: general_product_id, order_id: @order.id, quantity: 1, price: Product.find(general_product_id).price)
        params[:order_item].each do |key, value|  
          if value[:quantity].to_i != 0 
            OrderItem.create!(product_id: key, order_id: @order.id, quantity: value[:quantity], price: Product.find(key).price, additional: true)
          end  
        end  
        format.html { redirect_to root_path, notice: 'Ваш заказ успешно создан! Ожидайте звонка оператора.' }
      else
        format.html { render :calculate }
      end
    end



  end 

  def about 
    @page_title = 'Наши контакты'
  end  

  private

      # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:order).permit(:name, :email, :phone, :variant, :eco, :get_key)
    end


end

app/views/welcome/_additional.html.haml
.row.withHint
  = label_tag :additional do
    = additional.name
    =link_to nil, class: 'info' do
      %div
        %span
        = additional.description
    %span
      = additional.price 
      = additional.unit 
  .spinner
    %a{:href => "", class: "less"}
    = number_field_tag "order_item[#{additional.id}][quantity]", 0, in: 0...10
    %a{:href => "", class: "more"}

app/views/welcome/about.html.haml
=render 'main_menu'
    
.contactsSpace
  %div
    .leftSpace
      %h2 О компании
      #content__contact__contact__1__about.adminTextEl
        %p
          %b Бэст Клин
          начал свою деятельность еще в 2014 году. Небольшая&nbsp;группа&nbsp;клинеров, специализирующихся, в основном на&nbsp;уборке квартир в одной из крупных Российских компаний решила организовать собственное предприятие, на базе которого и образовался теперешний Bjic.
        %p Особый акцент в своей деятельности мы стараемся делать на качество предоставляемых услуг и на сотрудничество на постоянной основе, что дает нашим клиентам непременную уверенность в совместном сотрудничестве. Большинство&nbsp;по достоинству ценят наше внимание, скорость, профессионализм и желание предоставить действительно качественный сервис для любых, даже самых требовательных клиентов.
        %p
          С уважением,
          = succeed "." do
            %b Коллектив Bjic
    .rightSpace
      %h2 Наш адрес
      #content__contact__contact__1__central.adminTextEl
        %p Москва, Ул. Миклухо-Маклая 36, к1
        %h3
          %strong
            \&quot;Бэст Клин&quot; или просто
            %span{:style => "color:#FF8C00;"} Bjic
        %p
          Телефон:
          %strong +7 (800) 500-71-42
        %p
          E-mail:
          %a info@bjic.ru
        %p
          %strong Работа в компании: +7 (499) 322-39-34
.partnersSpace
  %ul
    %li
      %img{:src => "uploads/nfc/partner1.png"}/
    %li
      %img{:src => "uploads/nfc/partner2.png"}/
    %li
      %img{:src => "uploads/nfc/partner3.png"}/
    %li
      %img{:src => "uploads/nfc/partner4.png"}/
    %li
      %img{:src => "uploads/nfc/partner5.png"}/

app/views/welcome/calculate.html.haml
=render 'main_menu'

= javascript_include_tag "assets/calc.js"
= form_tag confirmation_path, method: 'post' do 
  / = render 'errors', object: @products

  .calculateSpace.unregistered
    %div
      .top

      .content
        .leftSpace
          %h1 Калькулятор
          .row
            = label_tag 'flattype' do
              Основная услуга
              =link_to nil, class: 'info' do
                %div
                  %span
                  1 - комн от 0 - 50 м2, 2 комн. от 0 - 70 м2, 3 комн. от 0 - 100 м2, 4 комн. от 0 - 150 м2
            .selector
              = collection_select 'order', 'product_id', @general_products, :id, :name
              
          .row
            = label_tag 'order[variant]' do 
              Тип уборки
              =link_to nil, class: 'info' do
                %div
                  %span
                  Выберите тип уборки
              %span
                %a{:href => "#what"} Что входит в уборку?
            .selector
              = select_tag 'order[variant]', options_for_select([['Быстрая', 'standart'], ['Генеральная', 'general'], ['После ремонта', 'remont']])
          %p Дополнительные услуги
          = render partial: 'additional', collection: @additional_products
          .row.withHint
            = label_tag 'order[eco]' do 
              Эко-уборка
              =link_to nil, class: 'info' do
                %div
                  %span
                  Полная эко уборка квартиры - Ecover, Kiehl
              %span +40% к стоимости
            .checkbox
              = check_box_tag 'order[eco]', false
          .row.withHint
            = label_tag 'order[get_key]' do 
              Заехать за ключами от квартиры
              =link_to nil, class: 'info' do
                %div
                  %span>
                  Если у вас совсем нет времени, мы поможем :)
              %span 300 руб.
            .checkbox
              = check_box_tag 'order[get_key]', false

        .rightSpace
          .totalSpace
            %h4 Уборка квартиры с 1 жилой комнатой и одной ванной
            .additional
              %span Дополнительно
              %p Мытьё духовки / СВЧ внутри
              %p Глажка
            %div
              %p К оплате
              %p.total
                %span> 4000
                3500 руб.
              %input{:name => "total", :type => "hidden", :value => "0"}/
              %input{:name => "freeWindow", :type => "hidden", :value => "false"}/
              %input{:name => "standartDiscount", :type => "hidden", :value => "false"}/
              %input{:name => "generalDiscount", :type => "hidden", :value => "false"}/
              %input{:name => "remontDiscount", :type => "hidden", :value => "false"}/
              %input{:name => "comment", :type => "hidden", :value => ""}/
              %input{:name => "totalCost", :type => "hidden", :value => "0"}/
              %input{:name => "discount", :type => "hidden", :value => "0"}/
          .row
            = text_field_tag 'order[name]', nil, placeholder: 'Ваше имя'
          .row
            = text_field_tag 'order[email]', nil, placeholder: 'Электронная почта'
          .row
            = text_field_tag 'order[phone]', nil, placeholder: 'Контактный телефон'
          = submit_tag 'Заказать уборку', { class: 'submit' }
          / %a.submit{ href: confirmation_path, method: 'post' } Заказать уборку
          %ul.miniFaq
            %li
              %h4
                %a{:href => "#what"} Что входит в уборку
            %li.accordion
              %h4 Расценки на уборку
              #content__calculate__calculate__1__p1.adminTextEl
                %p
                  %strong> Расценки на уборку кварир
                  \&nbsp;строго соответствуют заявленным в калькуляторе.
                  %br/
                %p
                  Вы можете сами&nbsp;
                  %strong> рассчитать стоимость уборки
                  , выбрать дополнительные услуги, и сделать заказ. &nbsp;
                %p Мы работаем без доплат и изменений цен "на месте"!
                %p В случае нестандартных уборок или иных вопросов, возникающих в процессе уборки, убедительно просим связаться с нами для уточнений и корректировок.
                %p В калькуляторе используется следующая классификация квартир:&nbsp;
                %blockquote
                  %p{"data-mce-style" => "text-align: left;", :style => "text-align: left;"}
                    %span{"data-mce-style" => "text-decoration: underline;", :style => "text-decoration: underline;"}
                      %strong 1 &nbsp;комн от 0 - 50 м2
                  %p{"data-mce-style" => "text-align: left;", :style => "text-align: left;"}
                    %span{"data-mce-style" => "text-decoration: underline;", :style => "text-decoration: underline;"}
                      %strong 2 комн. от 0 - 70 м2
                  %p{"data-mce-style" => "text-align: left;", :style => "text-align: left;"}
                    %span{"data-mce-style" => "text-decoration: underline;", :style => "text-decoration: underline;"}
                      %strong 3 комн. от 0 - 100 м2
                  %p{"data-mce-style" => "text-align: left;", :style => "text-align: left;"}
                    %span{"data-mce-style" => "text-decoration: underline;", :style => "text-decoration: underline;"}
                      %strong 4 комн. от 0 - 150 м2
            %li.accordion
              %h4 Приблизительное время уборки
              #content__calculate__calculate__1__p4.adminTextEl
                %p{"data-mce-style" => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;", :style => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;"} Приблизительное время уборки квартир:
                %p{"data-mce-style" => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;", :style => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;"}
                  \&nbsp;
                  %br/
                %p{"data-mce-style" => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;", :style => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;"} 1 комнатная ~ 1.5 - 3 часа
                %p{"data-mce-style" => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;", :style => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;"} 2 комнатная ~ 2 - 5 часов
                %p{"data-mce-style" => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;", :style => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;"} 3 комнатная ~ 5 - 8 часов
                %p{"data-mce-style" => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;", :style => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;"} 4 комнатная ~ 6 - 10 часов
                %p{"data-mce-style" => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;", :style => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;"}
                  \&nbsp;
                  %br/
                %p{"data-mce-style" => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;", :style => "text-indent: 0px; margin-bottom: 0px; margin-top: 0px;"} Однако, мы стремимся не ограничивать уборку по времени, для нас главное - результат. Пожалуйста планируйте свое время заранее.
            %li.accordion
              %h4 Кто приедет убирать?
              #content__calculate__calculate__1__p5.adminTextEl
                %p
                  %ul
                    %li - Славяне
                    %li - Профессионалы своего дела
                    %li - Только прошедшие профессиональный отбор
                  %br/
                %p
                  /%img{:alt => "", "data-mce-src" => "#", :height => "375", :src => "uploads/photostore/1446763669973.jpg", :width => "500"}/
                %p Сотрудники постоянно проходят внутреннюю курсы повышения квалификации на базе наших партнеров, производителей чистящих средств мирового класса. Весь необходимый инвентарь наши клинеры всегда приносят с собой.
:javascript
  var standart = new Array();
  var general = new Array();
  var remont = new Array();
  standart[1] = 1500;
  standart[2] = 1800;
  standart[3] = 2000;
  standart[4] = 2900;
  general[1] = 2900;
  general[2] = 3900;
  general[3] = 4900;
  general[4] = 5900;
  remont[1] = 5500;
  remont[2] = 6500;
  remont[3] = 8500;
  remont[4] = 9500;
  var wc = 300;
  var bal = 500;
  var okno = 250;
  var lustra = 200;
  var holod = 300;
  var duhov = 300;
  var glad = new Array();
  glad[1] = 300;
  glad[2] = 150;
  glad[3] = 700;
  var getkey = 300;
  var fast = 2000;
  var eco = 40;
.bottom
%a{:name => "what"}

app/views/welcome/index.html.haml
.orderSpace.pc{ style: "background-image: url(assets/bg1.jpg);" }

=render 'main_menu'
.standartArticleSpace
  #content__about__about__1__p5.adminTextEl
    %h1 О сервисе и качестве услуг:

    %div В своей работе наши специалисты применяют только самые современные чистящие и моющие средства. В своей деятельности мы руководствуемся профессионализмом как в части обслуживания, так и в найме персонала. Наши клинеры постоянно проходят повышение квалификации, после которого силами наших партнеров мы производим &quot;Контрольную закупку&quot; от стороннего заказчика, о котором не знают даже топ-менеджеры нашей организации. Все это на регулярной основе позволяет контролировать качество предоставляемых услуг. Большинство наших клиентов предпочитают сотрудничать с нами на постоянной основе по предварительно согласованному графику уборок в их квартирах. Руководствуясь удовлетворенностью от качественно предоставленных услуг нас с удовольствием рекомендуют своим друзьям и знакомым в части клининговых услуг, а это лучший показатель качества нашей работы.

    %div &nbsp;

    %div Ни один звонок и ни одно обращение не проходят мимо нашей клиентской службы. Уже со второго заказа мы предоставляем скидку на уборку Вашей квартиры.

    %div &nbsp;

    %strong С уважением, Команда Bjic.

%hr
.optionsSpace
  %h4 Наши приемущества:

  %ul
    %li.option1 
      %strong Без предоплаты! 
      Оплата производится после выполнения работ!
 
    %li.option2
      %strong Гарантии!
      Что-то не понравилось? Исправим!

    %li.option3
      %strong Выезжаем за МКАД!
      Если есть возможность добраться на метро!

    %li.option4
      %strong Без доплат
      Никаких дополнительных платежей на месте. Только оговоренная по заказу сумма!


    %li.option5
      %strong Индивидуальный подход
      Дополнительные услуги обговариваются отдельно

.khimSpace.pc{ style: "background-image: url(assets/bg2.jpg);" } &nbsp;

.col2Space
  %ul
    %li
      #content__about__about__1__col1.adminTextEl
        %p
          %strong Клининговая компания Bjic
          &mdash; Услуги по уборке квартир по Москве.

        %p Заказав у нас уборку квартиры Вы экономите личное время, которое можете потратить на более приятные моменты в жизни, такие, как общение с семьей, развлечения и работу...

        %p В своей работе мы выбираем лишь самые современные экологичные средства уборки и современное оборудование.
    %li
      #content__about__about__1__col2.adminTextEl
        %p Все услуги предоставляются в рамках санитарных требований и правил по уборке квартир и жилых помещений.

.partnersSpace
  %ul
    %li <img src="uploads/nfc/partner1.png"
    %li <img src="uploads/nfc/partner2.png"
    %li <img src="uploads/nfc/partner3.png"
    %li <img src="uploads/nfc/partner4.png"
    %li <img src="uploads/nfc/partner5.png"

app/views/welcome/promotion.html.haml
=render 'main_menu'

.orderSpace.pc{:style => "background-image: url(uploads/slider/1445538625379-2.jpg);"}
  / <h2 class="c1"></h2>
%p{:style => "text-align: center;"}
  %span{:style => "font-size:36px;"}
    %span{:style => "font-family:comic sans ms,cursive;"}
      %span{:style => "color:#FF8C00;"} !!Предновогодняя акция!!
%p{:style => "text-align: center;"}
  %span{:style => "font-size:18px;"}
    %strong На заказ генеральной&nbsp;уборки квартиры с 15 декабря по 26 декабря 2015 года скидка сделавшим заказ через сайт
%p{:style => "text-align: center;"}
  %span{:style => "font-size:72px;"}
    \-- 20
    %span{:style => "color:#FF0000;"}> %
    \&nbsp;--
.khimSpace.pc{:style => "background-image: url(uploads/slider/1445538362591-2.jpg);"}
  / h2 class="c3"></h2
%hr