config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
   
  scope '/', controller: :welcome do
    get 'index'
    get 'about'
    get 'calculate'
    get 'promotion'
    post 'confirmation'
  end

  scope '/', controller: :calculators do
    get 'index'
  end
  

  namespace :admin do
    resources :products
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  respond_to :html, :xml, :json
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_admin_nav.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#main-nav", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "Bjic Admin", admin_pages_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    #main-nav.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          =link_to "Content", admin_pages_path
        %li
          =link_to "Employe", admin_employes_path
        / %li
        /   =link_to "Orders", admin_orders_path
        / %li
        /   =link_to "General service", admin_generals_path
        / %li
        /   =link_to "Additional service", admin_additionals_path
        / %li
        /   =link_to "Product", admin_products_path


      / -if user_signed_in?
      /   %ul.nav.navbar-nav.navbar-right
      /     %p.navbar-text
      /       Signed in as #{current_user.name}.
      /       =link_to "Log out.", destroy_user_session_path, method: :delete

app/views/application/_errors.html.haml
- if object.errors.any?
  #error_explanation
    %h2= "#{pluralize(object.errors.count, "error")} prohibited this #{object.class} from being saved:"
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/application/_footer.html.haml
.bottomSpace
  %ul
    %li
      %strong Уборка квартир
      =link_to 'Уборка квартир в Москве', nil
      =link_to 'Генеральная уборка', nil
      =link_to 'Уборка после ремонта', nil
      / %a{:href => "/calculate#content__calculate__calculate__1__col1"} Уборка квартир в Москве
      / %a{:href => "/calculate#content__calculate__calculate__1__col2"} Генеральная уборка
      / %a{:href => "/calculate#content__calculate__calculate__1__col3"} Уборка после ремонта
    %li
      %strong О компании
      =link_to 'Работа', nil
      =link_to 'Кто приедет убирать', nil
      =link_to 'Пользовательское соглашения', nil
      / %a{:href => "/contacts"} Работа
      / %a{:href => "/calculate#content__calculate__calculate__1__p5"} Кто приедет убирать
      / %a{:href => "/#"} Пользовательское соглашения
    %li
      %strong Адрес и время работы:
      %p
        Работаем с 8:00 до 24:00
        %br/
        ежедневно и без выходных.
      %p.address
        Москва,
        %br>/
        Ул. Миклухо-Маклая 36, к1
    %li
      %strong Телефон:
      %p.phone
        %b +7 (800) 500-71-42
      %p.phone
        %b +7 (499) 322-39-34
    .copyright
      @CMS-all, Все права защищены. По техническим вопросам просьба писать администратору сайта admin@bjic.ru
    .arrowUpSpace
      %a.arrowUp{:href => "#"}
      #forAjaxSpace

app/views/application/_header.html.haml
.headSpace
  %ul
    %li.logo=link_to (image_tag 'logo.svg', alt: 'Перейти на главную страницу сайта'), root_path  #, class: 'navbar-brand hidden-xs'
    %li.order=link_to 'Заказать уборку', calculate_path
    %li.personal
      %b Все услуги оказывают славяне.
      %br
      %b Все работы застрахованы.
    %li.phone
      %span 
        %b +7 (800) 500-71-42
      %hr
      %span 
        %b +7 (499) 322-39-34 
      %br 
        %b Работаем с 08 до 24 ч.

app/views/application/_main_menu.html.haml
.mainMenuSpace
  %ul
    %li.calculate=link_to 'Рассчитать стоимость уборки квартиры', calculate_path
    %li.service=link_to 'Акции и Скидки', promotion_path
    %li.about=link_to 'О компании', about_path

app/views/application/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->